### ISSUE TITLE
Test passport PR with latest stable gluu-server build.

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/gluu-passport-testing#30]
NOW it's like this:
- we can test new builds

we need to add this feature:
- Test passport PR with latest stable build.

**As a developer
I want to test my changes with last passport build
So I can ensure quality**

```gherkin
Scenario: Raising PR
Given I have a new branch
When I raise PR
Then I want to run stage integration tests w/ last gluu-Then server build
```

So what we need to do is:
- [x] create snapshot with latest stable gluu-server version 
- [x] on init, droplet should upgrade passport version inside chmod
- [x] create trigger on passport test jenkins

**Comment by christian-hawk** [comment]
@kdhttps any thoughts on how to achieve it?

I was thinking on running `gluu.sh` from command-line / Jenkins with PR number as an argument, something like
```bash
ssh /test-data/gluu.sh --pr 30
```

**Comment by kdhttps** [comment]
@christian-hawk  agreed :+1:
