### ISSUE TITLE
Load existing vars from config file CLI option

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/gluu-passport-testing#36]
Option on `env.sh` script, load existing vars from ENV.

We should load [this existing vars](https://github.com/GluuFederation/gluu-passport-testing/blob/7f60f51ee277d459f18ceaa73f31a7dc399b2887/env.sh#L39) from ENV.

Something like `--load-from-env`, other suggestions are welcome.

**Comment by kdhttps** [comment]
> Something like --load-from-env, other suggestions are welcome.

I think instead of `--load-from-env`, load config from `env` first if `env` is existed otherwise load default value.

**Comment by christian-hawk** [comment]
hey @kdhttps I also thought about this option.
I'm not sure which is best, my only concern is if is the env has any variable setup b4 with other goals (like `API_CLIENT_ID`).
Anyway I think is also acceptable. 👍🏻

**Comment by kdhttps** [comment]
There are two options:
1. instead of `--load-from-env`, load config from `env` first if `env` is existed otherwise load default value.
2. Take config only from env?

@christian-hawk  could you please confirm with which option are you agree?

I think the second option is good.

**Comment by christian-hawk** [comment]
first option, is good to avoid env variables as they are not safe... 
I think maybe we can change this issue to "load from env or config file", and we do something like `stage-test.conf`.

Agree?
