### ISSUE TITLE
Github Action (version bump) failing when no increment

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/gluu-passport-testing#41]
There is no impact but the latest push, if there is no increment, will show an `x` (failed).

It's a known bug https://github.com/commitizen-tools/commitizen/issues/280

And I already raised PR: https://github.com/commitizen-tools/commitizen/pull/284

**Comment by christian-hawk** [comment]
@kdhttps any thoughts?

**Comment by kdhttps** [comment]
Great Job about PR. If it is possible to use your version then we should use it.

**Comment by christian-hawk** [comment]
> Great Job about PR. If it is possible to use your version then we should use it.

 PR commitizen-tools/commitizen#284 accepted. Updating.
